#!/usr/bin/env python3
"""
Clipper Simulator
=================
模拟 Obsidian Web Clipper 浏览器扩展在 mp.weixin.qq.com 上的抓取行为。

真实环境下 Clipper 跑在 Chrome 里:
  1. 用户打开公众号文章
  2. content script 抓 #js_content / #activity-name / #publish_time / #js_name
  3. Readability.js + turndown 转 md
  4. 调 Obsidian 内置 CLI 写 vault

本脚本在命令行模拟同一个流程,但用 chatlog sqlite 里的 desc(摘要)
代替正文,因为命令行 curl 会被微信反爬挡。

注意:这是端到端 demo,不是真实产品代码。真实产品用 Obsidian Web Clipper。
"""
import json
import re
import sqlite3
import sys
import urllib.request
import urllib.parse
from datetime import datetime
from pathlib import Path

CHATLOG_DB = "/tmp/chatlog-decrypted/db_storage/message/biz_message_0.db"
CONTACT_DB = "/tmp/chatlog-decrypted/db_storage/contact/contact.db"
CHATLOG_ARCHIVE_DB = "/tmp/chatlog-decrypted/biz_archived.db"
CHATLOG_HTTP = "http://127.0.0.1:5030"
VAULT = Path("/tmp/obsidian-vault")


def http_get(path):
    with urllib.request.urlopen(f"{CHATLOG_HTTP}{path}", timeout=10) as r:
        return r.read().decode("utf-8")


def sanitize_filename(name):
    """Mirror Clipper's filename sanitizer (windows-illegal chars + trailing dots).

    Steps:
      1. replace any of `\\ / : * ? " < >` with `_`
      2. strip leading/trailing whitespace
      3. strip trailing dots and spaces (Windows hates trailing dots;
         we strip spaces too so a `. . .` tail doesn't leave a
         dangling space after `rstrip(".")`)
      4. cap at 120 chars
    """
    cleaned = re.sub(r'[\\/:*?"<>|]', "_", name).strip().rstrip(" .")[:120]
    return cleaned


def fetch_biz_metadata(gh_id, limit=20):
    """Hit chatlog HTTP API (same as the MCP tool query_biz_chat_log)."""
    body = http_get(f"/api/v1/bizchatlog?talker={gh_id}&limit={limit}")
    return body  # PlainText formatted


def fetch_biz_from_sqlite(gh_id):
    """Belt-and-suspenders: also pull from sqlite directly so we get URL+title+desc.

    Mirrors internal/wechatdb/datasource/v4/datasource.go:805 — chatlog reads
    `message_content` as bytes, and zstd-decompresses only when
    `WCDB_CT_message_content != 0` (the table's "compression tag" column).

    Returns an empty list if the per-ghID Msg_<md5> table doesn't exist
    (the public account has no local history).
    """
    import zstandard as zstd
    md5 = __import__("hashlib").md5(gh_id.encode()).hexdigest()
    table = f"Msg_{md5}"
    con = sqlite3.connect(CHATLOG_DB)
    cur = con.cursor()
    # Guard: table may not exist (wechat covers ~58% of followed accounts).
    exists = cur.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (table,)
    ).fetchone()
    if not exists:
        con.close()
        return []
    cur = con.cursor()
    # Match chatlog's exact SELECT columns (see v4/datasource.go:805)
    rows = cur.execute(
        f'SELECT create_time, local_id, sort_seq, local_type, message_content, '
        f'WCDB_CT_message_content FROM "{table}" ORDER BY sort_seq DESC LIMIT 20'
    ).fetchall()
    con.close()
    dctx = zstd.ZstdDecompressor()
    items = []
    for ct, local_id, sort_seq, local_type, content, content_ct in rows:
        # content_ct is the "WCDB compress tag"; non-zero means content is zstd'd
        if content_ct and content_ct != 0:
            try:
                content = dctx.decompress(content)
            except Exception:
                pass
        if not content:
            continue
        s = content.decode("utf-8", errors="ignore")
        title_m = re.search(r"<title><!\[CDATA\[(.*?)\]\]></title>|<title>(.*?)</title>", s)
        des_m = re.search(r"<des><!\[CDATA\[(.*?)\]\]></des>|<des>(.*?)</des>", s)
        url_m = re.search(r"<url><!\[CDATA\[(.*?)\]\]></url>|<url>(.*?)</url>", s)
        title = (title_m.group(1) or title_m.group(2)) if title_m else ""
        des = (des_m.group(1) or des_m.group(2)) if des_m else ""
        url = (url_m.group(1) or url_m.group(2)) if url_m else ""
        items.append(
            dict(
                title=title,
                desc=des,
                url=url,
                time=datetime.fromtimestamp(ct).isoformat(),
                sort_seq=sort_seq,
            )
        )
    return items


def lookup_account(gh_id):
    con = sqlite3.connect(CONTACT_DB)
    cur = con.cursor()
    nick = cur.execute(
        "SELECT COALESCE(nick_name, '') FROM contact WHERE username = ?", (gh_id,)
    ).fetchone()
    con.close()
    return nick[0] if nick else gh_id


def compose_md(item, account):
    """Mimic Clipper's `公众号/{{author}}-YYYY-MM-DD-{{title}}.md` template."""
    date = item["time"][:10]
    title_safe = sanitize_filename(item["title"])
    fname = f"{account}-{date}-{title_safe}.md"
    rel_path = f"公众号/{fname}"

    # Frontmatter mirrors Clipper's recommended schema (see chatlog biz2md --manifest)
    body = f"""---
ghID: ""
url: "{item['url']}"
author: "{account}"
publishedAt: "{item['time']}"
source: chatlog-biz2md-demo
tags:
  - 公众号
  - chatlog
---

# {item['title']}

> **NOTE**: This markdown was generated by the **chatlog biz2md end-to-end demo**,
> not by the real Obsidian Web Clipper. The "body" below is the abstract (des)
> from chatlog's local sqlite — the full article body requires a real
> browser session (Clipper captures it from rendered DOM).

{item['desc']}

---

*Archived from chatlog local sqlite at {datetime.now().isoformat()}*
*Original URL: {item['url']}*
"""
    return rel_path, body


def mark_archived(gh_id, url, title, source="clipper-simulator"):
    """Append to chatlog's biz_archived table — this is what Clipper would
    do via storage.local, but here we talk to chatlog's own DB directly."""
    con = sqlite3.connect(CHATLOG_ARCHIVE_DB)
    cur = con.cursor()
    cur.execute(
        "INSERT OR IGNORE INTO biz_archived (gh_id, url, title, archived_at, source) "
        "VALUES (?, ?, ?, ?, ?)",
        (gh_id, url, title, int(datetime.now().timestamp()), source),
    )
    con.commit()
    con.close()


def main():
    VAULT.mkdir(parents=True, exist_ok=True)
    (VAULT / "公众号").mkdir(exist_ok=True)

    gh_id = "gh_423b608e0744"
    account = lookup_account(gh_id)
    print(f"account: {account} ({gh_id})\n")

    print(">>> fetching from chatlog sqlite (simulating Clipper DOM capture)")
    items = fetch_biz_from_sqlite(gh_id)
    items = items[:3]  # only top 3 for demo

    archived = []
    for item in items:
        if not item["title"] or not item["url"]:
            continue
        rel_path, body = compose_md(item, account)
        full = VAULT / rel_path
        full.parent.mkdir(parents=True, exist_ok=True)
        full.write_text(body, encoding="utf-8")
        mark_archived(gh_id, item["url"], item["title"])
        archived.append(rel_path)
        print(f"  ✓ wrote {rel_path}  ({len(body)} bytes)")

    print(f"\n>>> {len(archived)} files written to {VAULT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())